version: '3.8'

services:
  app:
    build: .
    container_name: nestjs-app
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=root
      - DATABASE_NAME=todo_system
      - JWT_SECRET=secret_123
    depends_on:
      - db
    ports:
      - 3000:3000
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - todo-net

  db:
    image: postgres:13-alpine
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: todo_system
    ports:
      - 5433:5432
    networks:
      - todo-net
    volumes:
      - postgres-data:/var/lib/postgresql/data

networks:
  todo-net:
    driver: bridge

volumes:
  postgres-data:
    driver: local
